---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jane-rolebinding
subjects:
- kind: ServiceAccount
  name: jane
  namespace: dev
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io
