---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ken-rolebinding
subjects:
- kind: ServiceAccount
  name: ken
  namespace: dev
roleRef:
  kind: Role
  name: view
  apiGroup: rbac.authorization.k8s.io

