apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nodeexporter
  labels:
    app: nodeexporter
spec:
  selector:
    matchLabels:
      app: nodeexporter     
  template:
    metadata:
      labels:
        app: nodeexporter
    spec:
      containers:
      - name: exporter
        image: quay.io/prometheus/node-exporter:latest
        ports:
        - containerPort: 9100
          protocol: TCP
