---
apiVersion: v1 # Версия API
kind: Pod # Объект, который создаем
metadata:
 name: web # Название Pod
 labels:  # Метки в формате key: value
   app: web
spec: # Описание Pod
 containers: # Описание контейнеров внутри Pod
   - name: web # Название контейнера
     image: 14kaksam88/my_apache:2.0 # Образ из которого создается контейнер
 initContainers:
   - name: init-container
     image: busybox:1.31.0
     command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
     volumeMounts:
       - name: app
         mountPath: /app
 volumes:
   - name: app
     emptyDir: {}
